### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by pl-marasco**
Here is the first version of the notebook with more comprehensive documentation. 
Would be nice to have some tips from all you.

### CODE REVIEW

**Comment by acocac** [comment]
@pl-marasco great work! thanks for sharing the first draft of the notebooks 🚀  I've make some initial changes related to styling and editing cells to be more tutorial-focused. I had some issues when logging to my EGI account so I wasn't able to experiment from the `openeo` section, unfortunately.

Overall, it was a great idea to split the large notebook. While the first notebook has a decent documentation, the other two still require of further info. For the exercise notebook, will you have sort of questions marks that participants should replace with the correct answer(s)? (see for example some ideas [here](https://github.com/kingsgeocomp/geocomputation/blob/master/Practical-02-Functions%20and%20Packages.ipynb)). Another alternative consist in leaving a sort of self-assesment section to be completed after the workshop (see for example [here](https://alan-turing-institute.github.io/rse-course/html/self_assessment/00_packaging_treasure.html). @annefou might have better ideas according to her experience in Galaxy trainings. 

Finally, we should use a common template across all notebooks.  For instance, the Pythia project has some interesting sections which we can adapt for the FOSS4G workshop. Other potential template is the EarthCube notebooks (see [here](https://github.com/earthcube2022/ec22_book)). The templates of the EnvDS book is more use case oriented so I am not sure if they fit the purpose of our notebooks. 

I'll restart my test of your notebooks tomorrow, after double checking what's wrong with my EGI acccount.

**Comment by pl-marasco** [comment]
<p>First line is there to explain why we need to rely on OpenEO as repository instead using the original source. </p><p> </p><p>Can you point me to a resource so that I can learn a little bit more about how STAC is implemented in opeEO ? </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>Good point , for me both works. At the top I would just introduce the general 'fil ruge' and then I would step into details. </p><p> </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>no no, this is only a place holders. </p><p>All this has to be shaped in a more digestible way.</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/13/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guillaumeeb** [comment]
I noticed you've closed this PR, but I still reviewed the first notebook and noticed a few typos. Don't know if it will be useful or not.

**Comment by pl-marasco** [comment]
@guillaumeeb , sorry I didn't notice all these notes, thanks a lot! very helpful. I merged all of them in the latest commit. 
As you already know the reference version will be the tutorial one.

**Pull request closed without merging**
