### PR TITLE
Python package and notebook update

### PR DESCRIPTION
**Pull request by pl-marasco**
Even if both (notebook and package)  are not fully ready I think that could be useful for all of you to have all the components needed to start testing the notebook

### CODE REVIEW

**Comment by annefou** [comment]
Great! You download geotiff, right?

**Comment by pl-marasco** [comment]
No data are in NetCDF format; GeoTiff can be downloaded through the legacy portal.

**Comment by annefou** [comment]
So they don't have Cloud-Optimized GeoTIFF? 

I would not suggest an end-user to download a 2GB netCDF to use a tiny portion for a study. I would tell them to use the legacy portal and order the portion they need.

**Comment by pl-marasco** [comment]
There is not an easy answer to your question; as already mentioned you can order GeoTIFF (not COG) through the portal but the manifest exposes only NetCDF files.  
Ordering can take up to a couple of hours (just to be positive) and that's why most of the users prefer to download the entire dataset and then resample it. 
In any case the notebook is entirely based on precooked subset.

**Comment by pl-marasco** [comment]
@acocac I'm not fully convinced, 
The point is to make a comparison over the same exact point and sliders can take longer to be defined over two different datasets.
In any case, I would love to change my mind once I have see an example. Could you provide me a working one?

**Comment by acocac** [comment]
@pl-marasco you can see some examples in the `hvplot` documentation (see [here](https://hvplot.holoviz.org/user_guide/Interactive.html#interactive)). You could play with another variable different to lat,lon. I think it would be nice all notebooks maximise interactive plotting where possible.

**Comment by pl-marasco** [comment]
Ahhh ok ... so isn't a specific note but more in general. Ok, as there is already an example of `hvplot` with a slider on the time dimension I thought that was enough but in any case I will add some more example. As already mentioned feel free to create a merge request on my fork if you have any idea

**Comment by rsignell-usgs** [comment]
Is there a way to access the data from cloud object storage instead of download?

**Comment by pl-marasco** [comment]
@rsignell-usgs not that I know 

The only alternative I could imagine would be to fully rely on OpenEO. 
I've tested the option to make a STAC request but unfortunately seems that there is an issue that has been confirmed by the distributor.
Moreover, even if the idea of using OpenEo isn't bad per se, not all the products are available; Long Term Statistics are not.
 
An option could be to mix the approaches; store the LTS directly on the EGI deployment and download the S3 NDVI  time series through the Vito OpenEO https://openeo.vito.be . 

Later on, to give everybody the possibility to run the notebook, a copy of the LTS data should be made available through Zenodo as @annefou suggested.

**Comment by rsignell-usgs** [comment]
@pl-marasco , the reason I asked is because I've personally experienced a few workshops that struggled when step 1 was "download data".   Especially if this on a JupyterHub or Binder hub where the local filesystems are NSF mounted and slow.   What is the infrastructure that people will be using to run the notebooks?  (I apologize if this is already documented/discussed)

**Comment by annefou** [comment]
Thanks @rsignell-usgs You are right. Downloading datasets during a training can be challenging with poor wifi.
Datasets will be made available on the infrastructure. 

For the infrastructure, the plan is to use the jupyter deployment (jupyterhub + dask cluster) we are setting up on the European Open Science Cloud.

**Comment by pl-marasco** [comment]
@rsignell-usgs I'm really happy that you pointed out your perspective and experience on this. 
As seems that there are lots of concerns about this I decided to change the notebook and partially rely on the OpenEO infrastructure as already mentioned before; this will give us the possibility to select and download smaller areas avoiding big files. 

The LTS, as Anne mentioned, will be made available on the infrastructure. 

Once the stress test we are conducting is over, and if you are interested, you are more than welcome to test the entire notebook directly on the infrastructure.

**Comment by rsignell-usgs** [comment]
@annefou I tried googling but failed.  Is the European Open Science Cloud running on a commercial cloud provider, or is it running OpenStack/Cepf at an HPC center or something?

**Comment by guillaumeeb** [comment]
@rsignell-usgs currently, things are deployed on EGI, which make things much more clear [in term of Infrastructure](https://www.egi.eu/egi-infrastructure/). So this is closer to the second option, a federation of ressources of European data centers, often academic HPC facilities with some Openstack resources on it. 

EOSC is a bit blurry to me, this is kind of EGI 2.0, with more resources, and probably a part of commercial cloud, I'm really not sure of it. Maybe @annefou knows more about it.

**Comment by guillaumeeb** [comment]
First time I use ReviewNB, not convinced for now :), let's see the discussions.

Overall, there is probably to mich thing in this single notebook, I think you should split it, maybe before introducing Rioxarray and Zarr.

**Comment by annefou** [comment]
@rsignell-usgs 
@guillaumeeb already explains most of it. Thanks!

EOSC (European Open Science Cloud) is a federated cloud for research data to support EU science (https://eosc-portal.eu/about/eosc). There is not one single provider which can make EOSC difficult to navigate and understand.
In our case, resources are provided by CESNET (https://www.cesnet.cz/cesnet/?lang=en) in the framework of the EGI-ACE European project (https://www.egi.eu/project/egi-ace/). 
CESNET is providing cloud resources (CPU + later GPUs) with openstack. To facilitate deployments and promote EOSC, EGI-ACE develops a tool called IM (https://imdocs.readthedocs.io/en/stable/intro.html) is a tool that ease the access and the usability of IaaS clouds by automating the VMI selection, deployment, configuration, software installation, monitoring and update of Virtual Appliances. It supports APIs from a large number of virtual platforms, making user applications cloud-agnostic.

**Comment by pl-marasco** [comment]
<p>I don't know if that's possible and I have some doubts. What you can do is to achieve most of the things we do directly using OpenEO. But then the question is even to easy to ask... why not using entirely Open EO ? This is why I tried to push away the use of it. </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>Agree, is only there to remind me that I've to better describe all this terminology with some examples.</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>Conversion factor from Bytes to MB </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>Right, in the previous version of the notebook I was explaining all this through examples. The original datasets are coming with the correct attributes that define the scale and the shift and can shift from one to the other through the mask_scale parameter. Unfortunatelly, the OpenEO version doesn't allow this. </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>This comes from the past; instead of using a different band for the flags, some are directly coded in the NDVI values [251,252,253,254,255]. 255 stands for invalid pixels, 254 sea, 253 snow or cloud, etc.&nbsp;</p><p>The best option would have been to use the quality band in conjunction with these values but then I would have spent time explaining why they are coded in bits and most of the users get immediately lost.&nbsp;</p><p> </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>This is not a specific answer to your but is just to make the point of the situation.</p><p>&nbsp;</p><p>My original thought was to avoid OpenEO and take leverage of the STAC+Pangeo stack. Unfortunately, I run into lots of problems like:</p><p>&nbsp;</p><ul><li>As there is no way to make a REST request for data on the CGLS the only option I was able to imagine is a stupid facilitator that takes leverage of the manifest made available from VITO.&nbsp;&nbsp;</li><li>Files from the CGLS are more or less 2 GB each; almost all the participants in this discussion suggested avoiding the nightmare of downloading them live through low-speed WiFi.</li><li>There is no cloud object storage for these datasets; none of AWS GC Planetary computer or others has ingested it (most probably you can only find it on DIAS). If you need more details I can give you. Would be useful if a pool of users requested the ingestion from one of the big players &nbsp;&nbsp;</li><li>Copernicus Global Land Service has no STAC catalog; moreover, the STAC compatibility of the OpenEO version isn't properly set up so the requests fail. I sent an email to ask for clarification and an update and the responsible answer me that they will achieve this on the next tender.</li><li>The only way to get data from the CGLS over a specific AOI is to make an order on the legacy portal. Right now request are even fast to be processed but I can't imagine with 30 simultaneous. Moreover there is no option to have in NetCDF format, &nbsp;only in GeoTiff; this means that you will get a single file per each band you ordered (from my perspective is a nightmare that I would never like to teach as a correct approach). </li><li>I love all the concerns that you girls&amp;guys have about the CGLS distribution. Are already 5 years since I'm expressing my opinion on it and at least now I feel a little bit less alone.</li></ul>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>Second time I use ReviewNB and I don't like at all ... But I took the challenge </p><p>Ok, that's right .. but don't forget that I've a scientific target and the objective is to fine the balance between teach and create a product. </p><p> </p>

**Comment by guillaumeeb** [comment]
<blockquote>almost all the participants in this discussion suggested avoiding the nightmare of downloading them live through low-speed WiFi.</blockquote><p>The idea would be to download it from CESNET infrastructure, isn't it? But I agree this is still bad to dwnload it live with doens of users.</p><p> </p><blockquote>There is no cloud object storage for these datasets</blockquote><p> </p><p>Let's make one on CESNET with a subset!</p><p> </p><blockquote>Moreover there is no option to have in NetCDF format,&nbsp;only in GeoTiff; this means that you will get a single file per each band you ordered (from my perspective is a nightmare that I would never like to teach as a correct approach)</blockquote><p> </p><p>And you could have several bands in one GeoTiff. But anyway, this means if we download a (big) subset, we'll have to rework the data to make it analysis ready?</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guillaumeeb** [comment]
<p>I don't thinks it's possible currently, but don't you think it would be nice to be able to do that? It's probably feasible with some coding project, you must already have all the metadata for building a DataArray before downloading things.</p><p> </p><p>And for the question, yes I ask it! Maybe a point is when you want to do the processing at scale? How will OpenEO handle a processing on a wide area? Does it distribute things on CGL side?</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guillaumeeb** [comment]
<p>I would suggest to make it more explicit: </p><pre class="ql-syntax" spellcheck="false">print(f'{np.round(cgls_ds.NDVI.nbytes / 1024**2, 2)} MB')
</pre>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guillaumeeb** [comment]
<p>Then you should probably explain a bit this, just one or two sentences (but maybe it was foreseen).</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>yep, the notebook is an ongoing project and most of the comments are not there yet. Anyhow thanks to point me out.</p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>yes indeed and should be somthing that has to be discussed with the OpenEO counterpart. </p><p>I'm not an expert on OpenEO so I'm not the right person to ask, anyhow seems that if you need you can batch some computation directly on the server and just get results; that's something I would understand better especially in the vision of scalability over different platforms. </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<blockquote>The idea would be to download it from CESNET infrastructure, isn't it? But I agree this is still bad to dwnload it live with doens of users.</blockquote><p>No, data are not available from CESNET so we have to rely on VITO</p><p> </p><blockquote>&nbsp;Let's make one on CESNET with a subset!</blockquote><p>That was my first suggestion and then we opt for make the notebook more usable and let users download the data. </p><p> </p><blockquote>And you could have several bands in one GeoTiff. But anyway, this means if we download a (big) subset, we'll have to rework the data to make it analysis ready?</blockquote><p>Nope, if you order data from VITO you can't as they will split bands in different files. &nbsp;A pre cook dataset will be made available on the </p><p> </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by guillaumeeb** [comment]
<blockquote>No, data are not available from CESNET so we have to rely on VITO</blockquote><p>Yeah, I was meaning that users should be on CESNET infrastructure when they download data, so hopefully, they have a good bandwidth.</p><p> </p><blockquote>That was my first suggestion and then we opt for make the notebook more usable and let users download the data.</blockquote><p>This is great to show these steps. But as we are talking of scaling, we could need a pre-download.</p><p> </p><blockquote>Nope, if you order data from VITO you can't as they will split bands in different files.</blockquote><p>Right, I didn't want to say you can have it that way on VITO, but that it would be possible, that was unclear.</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>Something is wrong in OpenEO then, missing all relevant attributes (metadata) :/ Is it only related to the version? Is it in their project roadmap? </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>I can't answer to your request as I'm not involved in the decision process. </p><p>Any how I was a little bit surprised too but most probably in a couple of days I'm going to revert some part of the notebook as I realized that is too important demonstrate some component that through OpenEO can't be highlighted. </p><p>  </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>Thanks !!! I didn't had any idea as I'm not use to work with GeoPandas :-)</p><p> </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>No worries, it'll be good to report these to OpenEO. It seems the EO developers share their roadmap through the GitHub repository milestones, see here: https://github.com/Open-EO/openeo-api/milestones. </p><p> </p><p>Information loss is well-addressed in rioxarray, https://corteva.github.io/rioxarray/html/getting_started/manage_information_loss.html?highlight=gdal. Not sure how OpenEO handles their collections and why they're missing such relevant attributes, unfortunately. </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by pl-marasco** [comment]
<p>There is no real lost of attributes, data are correctly distributed according to the PUM.</p><p>In any case IMHO is more related on how Terrascope/VITO has implemented the OpenEO server. Most probably this data repository is even considered a beta so we only have to be glad that they did what they did. </p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/pangeo-data/foss4g-2022/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
