### PR TITLE
Fixes #22 move NOTEBOOKS to tutorial/examples

### LINKED ISSUE #22: Where should the Notebooks go?
Currently, there are two main folders: NOTEBOOKS (not fond of the upper case style), and tutorial. In tutorial: notebooks.

I'm under the impression that all notebooks that workshop participants want to see should be in tutorial/notebooks.

If so, we should move important content from NOTEBOOKS folder to tutorial/notebooks, and either remove the NOTEBOOKS folder, or rename it in a way it is clear that its content is not important for learning about Pangeo.

Anyway, I think we should clarify things here.

### PR DESCRIPTION
**Pull request by annefou**
And only build jupyter book for notebooks listed in the TOC

### CODE REVIEW

**Comment by pl-marasco** [comment]
fine by me, 

@acocac, are you agree with this?

**Review by guillaumeeb — APPROVED** [review]
Thanks @annefou, LGTM.

**Review by pl-marasco — APPROVED** [review]
Nothing to add, 
@annefou thanks!

**Review by acocac — APPROVED** [review]
LGTM! We could consider to submit some of them, xarray and wildfires ones later to the EDS book. Let's discuss it in the final FOSS4G preparation meeting or Pangeo EU coffee meeting next week.

**Pull request merged**
